#!/bin/bash
echo "🚀 Deploying CareerPath Backend to Render..."
echo ""
echo "📋 INSTRUCTIONS:"
echo ""
echo "1. Go to: https://render.com"
echo "2. Click 'Get Started for Free'"
echo "3. Sign up with GitHub (takes 30 seconds)"
echo ""
echo "4. Once logged in:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Select 'Build and deploy from a Git repository'"
echo "   - Click 'Use public Git repository'"
echo ""
echo "5. For now, we'll use the Render Dashboard to deploy"
echo ""
echo "🔗 Render Dashboard: https://dashboard.render.com"
echo ""
echo "I'll create a render.yaml file that Render will auto-detect!"
